#!/usr/bin/env python3
# ============================================================================
# edgeai_train.py - Vecta "Edge AI" modulu icin gercek TFLite Micro modeli uret.
#
#   Cihaz OGREN modunda her ornegin 24-boyutlu ozellik vektorunu Seri Port'a
#   basar:   EAIFEAT,<sinif>,f0,f1,...,f23
#   Bu satirlari bir dosyaya kaydet (pio device monitor > data.csv) ve:
#
#       python tools/edgeai_train.py data.csv > edgeai_model.h
#
#   Uretilen edgeai_model.h'yi proje koklerine koy, platformio.ini'deki TFLite
#   lib_deps satirini ac, derle + flasla. Cihaz artik egitilmis sinir agini
#   kullanir (mod_edgeai.h -> eaiClassify -> eaiTfliteInfer).
#
#   Model sozlesmesi (firmware ile AYNI olmali):
#     girdi  float32 [1,24]   cikti float32 [1,N] softmax
#     Dense(24->16)+ReLU -> Dense(16->N)+Softmax
#
#   Gereksinimler:  pip install tensorflow numpy
# ============================================================================
import sys, numpy as np

FEAT = 24

def read_text(path):
    # PowerShell '>' UTF-16 (BOM) yazar; pio monitor UTF-8 de olabilir. Hepsini coz.
    raw = open(path, "rb").read()
    for enc in ("utf-8-sig", "utf-16", "utf-8", "cp1252"):
        try:
            return raw.decode(enc)
        except (UnicodeDecodeError, UnicodeError):
            continue
    sys.exit("Hata: dosya kodlamasi cozulemedi.")

def load(path):
    X, y = [], []
    for line in read_text(path).splitlines():
            line = line.strip()
            if not line:
                continue
            # "EAIFEAT,<slot>,f0,...,f23"  ya da  "<slot>,f0,...,f23"
            if line.startswith("EAIFEAT,"):
                line = line[len("EAIFEAT,"):]
            parts = line.split(",")
            if len(parts) < FEAT + 1:
                continue
            try:
                slot = int(float(parts[0]))
                feats = [float(v) for v in parts[1:1 + FEAT]]
            except ValueError:
                continue
            X.append(feats); y.append(slot)
    if not X:
        sys.exit("Hata: gecerli EAIFEAT satiri bulunamadi.")
    return np.array(X, np.float32), np.array(y, np.int32)

def main():
    if len(sys.argv) < 2:
        sys.exit("Kullanim: python edgeai_train.py data.csv [cikti_yolu]\n"
                 "  cikti_yolu verilmezse proje kokune edgeai_model.h yazilir.")
    # Cikti dosyasi: 2. arg ya da varsayilan olarak proje koku (tools'un ust klasoru).
    import os
    out_path = sys.argv[2] if len(sys.argv) > 2 else \
        os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "edgeai_model.h")

    import tensorflow as tf

    X, y_raw = load(sys.argv[1])
    # slot etiketlerini 0..N-1'e sirala (model ciktisi = bu sirayla)
    labels = sorted(set(int(v) for v in y_raw))
    remap  = {s: i for i, s in enumerate(labels)}
    y = np.array([remap[int(v)] for v in y_raw], np.int32)
    N = len(labels)
    print(f"// {len(X)} ornek, {N} sinif (slotlar: {labels})", file=sys.stderr)
    if N < 2:
        sys.exit(f"Hata: en az 2 farkli sinif gerek (su an {N}). Cihazda Edge AI > "
                 "OGREN'de BASKA bir slota (Ses 2) da ses ogret, tekrar kaydet.")

    model = tf.keras.Sequential([
        tf.keras.layers.Input((FEAT,)),
        tf.keras.layers.Dense(16, activation="relu"),
        tf.keras.layers.Dense(N, activation="softmax"),
    ])
    model.compile(optimizer="adam",
                  loss="sparse_categorical_crossentropy", metrics=["accuracy"])
    model.fit(X, y, epochs=200, batch_size=8, verbose=0)
    loss, acc = model.evaluate(X, y, verbose=0)
    print(f"// egitim dogrulugu: {acc:.3f}", file=sys.stderr)

    conv = tf.lite.TFLiteConverter.from_keras_model(model)
    conv.optimizations = [tf.lite.Optimize.DEFAULT]   # float fallback (girdi/cikti float32)
    tflite = conv.convert()

    # C header'i DOGRUDAN dosyaya yaz (ASCII, LF). stdout'a yazmiyoruz: boylece
    # PowerShell '>' UTF-16 sorunu ve TF'in stdout loglari ("Saved artifact...")
    # dosyaya karismaz.
    lines = ["// AUTO-GENERATED by tools/edgeai_train.py - do not edit by hand.",
             f"// {N} class(es): slots {labels}", "#pragma once", "",
             "alignas(16) const unsigned char g_edgeai_model[] = {"]
    for i in range(0, len(tflite), 12):
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in tflite[i:i + 12]) + ",")
    lines.append("};")
    lines.append(f"const unsigned int g_edgeai_model_len = {len(tflite)};")
    with open(out_path, "w", encoding="ascii", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"// model boyutu: {len(tflite)} bayt -> {out_path}", file=sys.stderr)

if __name__ == "__main__":
    main()
