#!/usr/bin/env python3
"""
png2mask.py - convert launcher icon PNGs into icon_masks.h (8-bit alpha masks).

Each PNG in the input folder becomes one IconMask, named by its filename
(e.g. clock.png -> id "clock"). The watch picks the right one by module id via
the generated iconFor(). Masks are blended in any colour over the disk -> they
keep the idle/focus recolour and have smooth (anti-aliased) edges.

USAGE
  pip install pillow
  # put white-on-transparent PNGs in Vecta/tools/icons/  named <moduleid>.png
  #   e.g. clock.png weather.png compass.png music.png buddy.png ...
  python tools/png2mask.py                 # -> Vecta/icon_masks.h, size 56
  python tools/png2mask.py --size 64       # bigger icons
  python tools/png2mask.py --invert        # for BLACK-on-white art (no alpha)

Module ids come from registerModule() in Vecta.ino (charm, tama, collar, game,
clock, badge, notify, audio, fidget, finder, buddy, compass, draw, knob,
lovebox, album, maps, weather, music, streak, pomo, capsule, camera, rps,
reflex, ttt, assistant, voicenote, settings, xiaozhi, openclaw, mirror, nav,
lyrics, rotate). Any id without a PNG falls back to the built-in vector icon.
"""
import argparse, os, re, sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow gerekli:  pip install pillow")

HERE = Path(__file__).resolve().parent
DEF_IN  = HERE / "icons"
DEF_OUT = HERE.parent / "icon_masks.h"   # next to Vecta.ino so __has_include finds it


def to_mask(path: Path, size: int, invert: bool) -> Image.Image:
    im = Image.open(path).convert("RGBA")
    r, g, b, a = im.split()
    # If the image is effectively opaque, derive alpha from luminance.
    if a.getextrema()[0] == 255:
        lum = im.convert("L")
        a = lum.point(lambda v: (255 - v) if invert else v)
    elif invert:
        a = a.point(lambda v: 255 - v)

    # crop to the non-empty bounding box, then fit into size x size with padding
    bbox = a.getbbox()
    if bbox:
        a = a.crop(bbox)
    pad = max(2, size // 14)
    inner = size - 2 * pad
    aw, ah = a.size
    scale = min(inner / aw, inner / ah)
    a = a.resize((max(1, int(aw * scale)), max(1, int(ah * scale))), Image.LANCZOS)
    canvas = Image.new("L", (size, size), 0)
    canvas.paste(a, ((size - a.size[0]) // 2, (size - a.size[1]) // 2))
    return canvas


def ident(name: str) -> str:
    return re.sub(r"[^0-9a-zA-Z_]", "_", name)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="indir", default=str(DEF_IN))
    ap.add_argument("--out", default=str(DEF_OUT))
    ap.add_argument("--size", type=int, default=56)
    ap.add_argument("--invert", action="store_true")
    args = ap.parse_args()

    indir = Path(args.indir)
    pngs = sorted(indir.glob("*.png"))
    if not pngs:
        sys.exit(f"PNG bulunamadi: {indir}  (oraya <moduleid>.png dosyalarini koy)")

    out = ["// AUTO-GENERATED by tools/png2mask.py - do not edit by hand.",
           "#pragma once", "#include \"platform.h\"", ""]
    table = []
    for p in pngs:
        mid = p.stem
        var = "IM_" + ident(mid)
        m = to_mask(p, args.size, args.invert)
        data = list(m.tobytes())   # mode "L": 1 byte/pixel, row-major
        out.append(f"static const uint8_t {var}_a[] PROGMEM = {{")
        for i in range(0, len(data), 24):
            out.append("  " + ",".join(str(v) for v in data[i:i + 24]) + ",")
        out.append("};")
        out.append(f"static const IconMask {var} = {{ {m.size[0]}, {m.size[1]}, {var}_a }};")
        out.append("")
        table.append((mid, var))

    out.append("static const IconMask* iconFor(const char* id) {")
    for mid, var in table:
        out.append(f'  if (strcmp(id, "{mid}") == 0) return &{var};')
    out.append("  return nullptr;")
    out.append("}")

    Path(args.out).write_text("\n".join(out), encoding="utf-8")
    kb = sum(m for _, _ in table for m in [args.size * args.size]) / 1024
    print(f"{len(table)} ikon -> {args.out}  (~{kb:.0f} KB flash, {args.size}px)")
    print("ids:", ", ".join(mid for mid, _ in table))


if __name__ == "__main__":
    main()
